			<div class="address_top_title">Основные направления</div>
		
			<ul class="nav_left">
				<li><a href="/konsultacia_urologa/zapisatsya-na-priem-k-urologu/">Записаться на прием к урологу</a></li>
				<li><a href="/konsultacia_urologa/lecheniye-prostatita-v-moskve/">Лечение простатита</a></li>
				<li><a href="/konsultacia_urologa/diagnostika-prostatita/">Диагностика простатита</a></li>
				<li><a href="/konsultacia_urologa/vosstanovlenie-potencii/">Восстановление потенции</a></li>
				<li><a href="/konsultacia_urologa/xronicheskii-prostatit/">Хронический простатит</a></li>
				<li><a href="/konsultacia_urologa/prichiny-prostatita/">Причины простатита</a></li>
				<li><a href="/konsultacia_urologa/simptomy-prostatita/">Симптомы простатита</a></li>
				<li><a href="/konsultacia_urologa/mochekamennaya-bolezn/">Мочекаменная болезнь</a></li>
				<li><a href="/konsultacia_urologa/pochechnaya-kolika/">Почечная колика</a></li>
				<li><a href="/konsultacia_urologa/uretrit/">Уретрит</a></li>
				<li><a href="/konsultacia_urologa/cistit/">Цистит</a></li>
				<li><a href="/konsultacia_urologa/prostatit/">Простатит</a></li>
				<li><a href="/konsultacia_urologa/infekcii-mochepolovyh-putei/">Инфекции мочеполовых путей</a></li>
				<li><a href="/konsultacia_urologa/ispravlenie-korotkoi-uzdechki-polovogo-chlena/">Исправление короткой уздечки полового члена</a></li>
				<li><a href="/konsultacia_urologa/lechenie-bolezni-peyroni/">Лечение болезни Пейрони</a></li>
				<li><a href="/konsultacia_urologa/lechenie-dobavochnoi-pochechnoj-arterii/">Лечение добавочной почечной артерии</a></li>
				<li><a href="/konsultacia_urologa/lechenie-ekstrofii-mochevogo-puzyrya/">Лечение экстрофии мочевого пузыря</a></li>
				<li><a href="/konsultacia_urologa/lechenie-ektopii-pochek/">Лечение эктопии почек</a></li>
				<li><a href="/konsultacia_urologa/lechenie-epispadii/">Лечение эписпадии</a></li>
				<li><a href="/konsultacia_urologa/lechenie-fimoza/">Лечение фимоза</a></li>
				<li><a href="/konsultacia_urologa/lechenie-gidronefroza/">Лечение гидронефроза</a></li>
				<li><a href="/konsultacia_urologa/lechenie-gipospadii/">Лечение гипоспадии</a></li>
				<li><a href="/konsultacia_urologa/lechenie-iskrivleniya-polovogo-chlena/">Лечение искривления полового члена</a></li>
				<li><a href="/konsultacia_urologa/lechenie-kisty-pridatka-yaichka/">Лечение кисты придатка яичка</a></li>
				<li><a href="/konsultacia_urologa/lechenie-kriptorhizma/">Лечение крипторхизма</a></li>
				<li><a href="/konsultacia_urologa/lechenie-polikistoza-pochek/">Лечение поликистоза почек</a></li>
				<li><a href="/konsultacia_urologa/lechenie-stenoza-pochechnoy-arterii/">Лечение стеноза почечной артерии</a></li>
				<li><a href="/konsultacia_urologa/lechenie-striktury-uretry/">Лечение стриктуры уретры</a></li>
				<li><a href="/konsultacia_urologa/lechenie-ureterocele/">Лечение уретероцеле</a></li>
				<li><a href="/konsultacia_urologa/lechenie-urologicheskih-zabolevaniy/">Лечение урологических заболеваний</a></li>
				<li><a href="/konsultacia_urologa/diagnostika-urologicheskikh-zabolevanij/">Диагностика урологических заболеваний</a></li>
				<li><a href="/konsultacia_urologa/lechenie-anomalii-razvitiya-organov-mochevydelitelnoy-sistemy/">Лечение аномалий развития органов мочеполовой системы</a></li>
				<li><a href="/konsultacia_urologa/lechenie-leikoplakii-mochevogo-puzyria/">Лечение лейкоплакии мочевого пузыря</a></li>
				<li><a href="/konsultacia_urologa/lechenie-mochekamennoi-bolezni/">Лечение мочекаменной болезни</a></li>
				<li><a href="/konsultacia_urologa/lechenie-muzhskogo-besplodiya/">Лечение мужского бесплодия</a></li>
				<li><a href="/konsultacia_urologa/lechenie-varikotsele/">Лечение варикоцеле</a></li>
				<li><a href="/konsultacia_urologa/muzhskaya-urologiya-i-andrologiya/">Мужская урология и андрология</a></li>
				<li><a href="/konsultacia_urologa/zhenskaya-urologiya/">Женская урология</a></li>
				<li><a href="/konsultacia_urologa/lechenie-balanopostita/">Лечение баланопостита</a></li>
				<li><a href="/konsultacia_urologa/lechenie-enureza/">Лечение энуреза</a></li>
				<li><a href="/konsultacia_urologa/lechenie-kavernita/">Лечение кавернита</a></li>
				<li><a href="/konsultacia_urologa/lechenie-vezikulita/">Лечение везикулита</a></li>
				<li><a href="/konsultacia_urologa/lechenie-pielonefrita/">Лечение пиелонефрита</a></li>
				<li><a href="/konsultacia_urologa/lechenie-adenomy-prostaty/">Лечение аденомы простаты</a></li>
				<li><a href="/konsultacia_urologa/lechenie-epididimita/">Лечение эпидидимита</a></li>
				<li><a href="/konsultacia_urologa/lechenie-novoobrazovanii-mochepolovyh-organov/">Лечение новообразований мочеполовых органов</a></li>
				<li><a href="/konsultacia_urologa/lechenie-orhita/">Лечение орхита</a></li>
				<li><a href="/konsultacia_urologa/lechenie-raka-mochevogo-puzyrya/">Лечение рака мочевого пузыря</a></li>
				<li><a href="/konsultacia_urologa/lechenie-raka-predstatelnoj-zhelezy/">Лечение рака Предстательной железы</a></li>
<!--<li><a href="/konsultacia_urologa/lechenie-uretrita/">Лечение уретрита</a></li>-->
				<li><a href="/konsultacia_urologa/lechenie-vospalitelnyh-zabolevanij-mochepolovoj-sistemy/">Лечение заболеваний мочеполовой системы</a></li>

			</ul><!--/nav_left-->